INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Ulric', 'Bollans', '1977-04-03', 'M', 'Tokyo')
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Shirlene', 'Sheals', '1971-04-19', 'F', 'Tokyo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Ernestine', 'Islep', '1974-04-09', 'F', 'Tokyo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Phil', 'Silby', '1984-05-16', 'F', 'Tokyo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Nara', 'Larwood', '1976-07-21', 'F', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Cristin', 'Rennick', '1991-04-30', 'F', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Bastien', 'Arch', '1996-07-11', 'M', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Clay', 'Nestor', '1981-01-03', 'M', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Annmaria', 'Grimshaw', '1976-08-28', 'F', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Alice', 'Marmyon', '1994-04-21', 'F', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Freddy', 'Macourek', '1994-01-08', 'F', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Umberto', 'Spondley', '1979-10-24', 'M', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Aarika', 'Summerell', '1976-09-02', 'F', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Tabatha', 'Ongin', '1989-12-26', 'F', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Constantino', 'Kingsland', '1985-07-06', 'M', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Dewain', 'Coppock', ',1982-02-19', 'M', 'Sydney');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Tyne', 'Trouel', '1975-03-09', 'F', 'Sydney');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Charlene', 'Burnet', '1984-09-11', 'F', 'Sydney');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Bev', 'Bailey', '1870-10-04', 'M', 'Sydney');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Farley', 'Ferrara', '1871-12-09', 'M', 'Sydney');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Ellie', 'Salters', '1978-11-15', 'F', 'Sydney');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Johnnie', 'Maulkin', '1987-02-05', 'M', 'Sydney');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Vilhelmina', 'Curtiss', '1889-03-07', 'F', 'tokyo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Peyter', 'Pickavance', '1879-08-08', 'M', 'tokyo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Cullen', 'Tredger', '1971-10-10', 'M', 'tokyo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Trixy', 'Mandel', '1980-02-07', 'F', 'Tokyo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Leela', 'Issit', '1979-03-26', 'F', 'Sydney');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Harland', 'Grzesiak', '1996-12-07', 'M', 'Sydney');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Cherry', 'Klimsch', '1988-02-07', 'F', 'Sydney');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Hillyer', 'Bartczak', '1996-05-30', 'M', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('John', 'Leggat', '1991-03-20', 'M', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Brigida', 'Drewitt', '1899-02-05', 'F', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Malissa', 'Sabbatier', '1872-05-23', 'F', 'Sydney');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Blinny', 'Tokell', '1978-11-08', 'F', 'Sydney');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Harriott', 'Kulis', '1981-09-30', 'F', 'Sydney');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Reynolds', 'Endley', '1986-10-27', 'M', 'Sydney');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Lyndsay', 'Clearley', '1987-04-04', 'F', 'Sydney');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Reggis', 'Peperell', '1875-06-02', 'M', 'Sydney');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Nat', 'Ramm', '1889-06-25', 'M', 'Sydney');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Adelaida', 'McHarry', '1890-05-07', 'F', 'tokyo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Angie', 'Darrington', '1970-06-21', 'F', 'Tokyo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Anneliese', 'Kolodziej', '1975-01-29', 'F', 'Tokyo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Benedicto', 'Ettles', '1996-01-17', 'M', 'tokyo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Fifi', 'Prigmore', '1892-08-20', 'F', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Sile', 'Madoc Jones', '1894-07-14', 'F', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Alfy', 'Fairbrother', '1996-01-07', 'F', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Arluene', 'Gerhardt', '1981-09-18', 'F', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Benjie', 'MacCrachen', '1983-10-30', 'M', 'tokyo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Giusto', 'Cromwell', '1972-07-07', 'M', 'Tokyo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Sander', 'Husselbee', '1980-04-23', 'M', 'tokyo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Meris', 'Nottingam', '1973-07-04', 'F', 'Tokyo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Hallie', 'Flisher', '1988-05-01', 'F', 'tokyo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Rheba', 'Jorat', '1984-09-26', 'F', 'tokyo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Karlens', 'Riggulsford', '1994-06-17', 'M', 'Tokyo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Clem', 'Farrand', '1996-01-24', 'F', 'tokyo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Bianka', 'Walkinshaw', '1993-11-24', 'F', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Ertha', 'Cooke', '1974-05-01', 'F', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Natassia', 'Parlett', '1975-11-26', 'F', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Frankie', 'McCullock', '1970-05-10', 'F', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Anakin', 'Skywalker', '1955-05-04', 'M', 'Tatooine');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Thurstan', 'Mordue', '1994-03-17', 'M', 'Tokyo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Carling', 'Harbach', '1970-01-20', 'M', 'Tokyo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Arlena', 'Lakenton', '1986-03-11', 'F', 'Tokyo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Abbie', 'Surmeir', '1982-01-03', 'F', 'Osaka');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Jennie', 'Pirri', '1989-01-28', 'F', 'Osaka');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Thurston', 'Stranahan', '1972-09-04', 'M', 'Osaka');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Hedwig', 'Tythe', '1974-01-15', 'F', 'Osaka');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Nicholle', 'Muirhead', '1994-07-23', 'F', 'Osaka');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Luke', 'Sievewright', '1994-11-26', 'M', 'Osaka');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Ambros', 'Colquite', '1991-07-08', 'M', 'Osaka');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Der', 'Jarrette', '1978-03-06', 'M', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Kaitlynn', 'Corneck', '1981-05-09', 'F', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Boigie', 'Sottell', '1999-09-07', 'M', 'Osaka');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Nathalia', 'Geneay', '1990-12-05', 'F', 'Osaka');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Patrizio', 'Cleft', '1974-03-17', 'M', 'Osaka');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Wandie', 'Roblett', '1982-08-27', 'F', 'Abuja');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Charles', 'Mager', '1983-11-06', 'M', 'Abuja');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Napoleon', 'Renak', '1970-12-16', 'M', 'Abuja');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Marnie', 'McCurlye', '1986-08-03', 'F', 'Abuja');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Bertie', 'Guidi', '1994-08-08', 'M', 'Abuja');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Anderea', 'Lowdyane', '1970-02-22', 'F', 'Abuja');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Pooh', 'Wimpenny', '1981-05-02', 'F', 'Abuja');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Mamie', 'Gisburne', '1999-05-29', 'F', 'Nairobi');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Jervis', 'Ruhben', '1973-02-13', 'M', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Abbye', 'Dadge', '1987-03-20', 'F', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Saunderson', 'Bolle', '1977-06-21', 'M', 'Nairobi');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Hastings', 'MacPake', '1981-08-04', 'M', 'Nairobi');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Branden', 'Leftridge', '1971-07-09', 'M', 'Nairobi');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Gerrie', 'Concannon', '1986-08-30', 'F', 'Nairobi');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Morie', 'Pregel', '1998-05-06', 'M', 'Nairobi');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Pebrook', 'Townley', '1997-01-22', 'M', 'Nairobi');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Filippo', 'Sherville', '1983-01-11', 'M', 'Sapporo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Pepita', 'Farloe', '1970-02-01', 'F', 'Sapporo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Berti', 'Zorer', '1972-08-19', 'M', 'Sapporo');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Putnam', 'Eliasen', '1980-01-31', 'M', 'Kyoto');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Nils', 'Groomebridge', '1990-07-21', 'M', 'Yokohama');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Gardy', 'Fairlie', '1999-05-08', 'M', 'Yokohama');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Lewiss', 'Adlem', '1988-06-15', 'M', 'Nagoya');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Rhett', 'Orman', '1975-08-14', 'M', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Foster', 'Langlais', '1977-07-11', 'M', 'San Francisco');
INSERT into students (first_name, last_name, date_of_birth, gender, town_of_origin) VALUES ('Merell', 'Browell', '1981-02-17', 'M', 'San Francisco');
